apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pf-api
  namespace: default
  annotations:
    cert-manager.io/issuer: 'letsencrypt-prod'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - k8s.progressionalfitness.com
      secretName: pf-api-tls
  rules:
    - host: k8s.progressionalfitness.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pf-api
                port:
                  number: 80
