# apiVersion: v1
# kind: Service
# metadata:
#   name: pf-api
# spec:
#   ports:
#     - port: 80
#       targetPort: 80
#       protocol: TCP
#   selector:
#     app: pf-api
apiVersion: v1
kind: Service
metadata:
  name: pf-service
  namespace: default
spec:
  selector:
    app: pf-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
