name: Deploy Nodejs Application

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" "MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}" >> .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t bkappel16/progressional-fitness-backend .
      - name: Publish image to docker hub
        run: docker push bkappel16/progressional-fitness-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull bkappel16/progressional-fitness-backend:latest
      - name: Delete old container
        run: docker rm -f progressional-fitness-backend
      - name: Run docker container
        run: docker run -d -p 80:3000 --name progressional-fitness-backend bkappel16/progressional-fitness-backend:latest
