name: Deploy Nodejs Application

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout source
        uses: actions/checkout@v4

      # Step 2: Login to Docker Hub
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker image with a unique tag
      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t bkappel16/progressional-fitness-backend:$IMAGE_TAG .

      # Step 4: Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push bkappel16/progressional-fitness-backend:${{ env.IMAGE_TAG }}

      # Step 5: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v4
        with:
          namespace: default
          manifests: |
            ./kubernetes/deployment.yaml
          images: |
            bkappel16/progressional-fitness-backend:${{ env.IMAGE_TAG }}
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
